# Generated by Django 4.1.3 on 2022-11-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='contenido',
            field=models.TextField(max_length=400),
        ),
    ]
